### ISSUE TITLE
박스구동시 아래의 그림과 같은 오류가 납니다!

### ISSUE THREAD

**Issue by bak35u** [lesstif/laravel-todolog#1]
뭐가 잘못된 것인가요?

![2016-05-25 08 01 56](https://cloud.githubusercontent.com/assets/6347943/15522673/176a6fec-224f-11e6-8c50-915b3e20afb5.png)

**Comment by lesstif** [comment]
@bak35u Windows 버전과 VirtualBox 버전이 어떻게 되나요?

찾아보니 http://stackoverflow.com/questions/33725779/failed-to-open-create-the-internal-network-vagrant-on-windows10 와 같은 글이 있는데 글에 나온대로 "**NDS6 Bridged Networking Driver**" 를 비활성화하고 확인을 눌러서 저장했다가 다시 활성화 하고 결과 공유해 주어요.

![image](https://cloud.githubusercontent.com/assets/404534/15525965/421e4bea-2269-11e6-9d28-62c4fd19a341.png)

**Comment by lesstif** [comment]
관련된 Ticket(https://www.virtualbox.org/ticket/15019)

**Comment by bak35u** [comment]
말씀하신대로 하니 되네요~ ^^ 
감사합니다!
