### ISSUE TITLE
리눅스에 대한 질문입니다.

### ISSUE THREAD

**Issue by y-minhoon** [lesstif/laravel-todolog#10]
저술하신 책에는 자세하게 나와 있지 않지만 블로그( www.lesstif.com ) 에 보니까 리눅스 설치에 대해서
우분투, 센트os 두 가지를 설명해 주셨는데요.
운영환경에서 그중에 추천할만한 OS(궁합이 잘 맞는?)가  있나요? 
아니면 2가지중에 아무거나 선정해도 지장이 없나요?

**Comment by lesstif** [comment]
둘 다 훌륭한 배포판이니까 개발이나 운영 조직에서 선호하는 배포판을 사용하시면 됩니다.

저는 개인적으로는 RHEL(Red Hat Enterprise Linux) 계열 배포판(CentOS 등) 을 선호합니다.

그래서 WAS 나 DB 서버같이 중요한 곳에는 RHEL를 사용하고 나머지 서버는 예산이 있을 경우 RHEL 을 없을 경우 CentOS 를 쓰는 편입니다.

**Comment by y-minhoon** [comment]
감사합니다.
