### ISSUE TITLE
p117 [그림 3.20] 템플릿 상속 

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#11]
오타도 아니고 잘못된 내용은 아니지만 정확하게 그림을 나타낸다고 가정한다면 
(개념적인 것은 맞습니다)

[그림 3.20] 의 task/list3.blade.php 는 

1) &lt;header&gt;, &lt;body&gt;, 태그를 삭제해야 합니다.
2) @section('title') 위에 @extends('layout.master') 가 삽입되어야 합니다.

아래와 같이

task/list3.blade.php

@extends('layout.master')
@section('title')
@section('content')

**Comment by lesstif** [comment]
@linuxwife 실제 blade template 은 지적해 주신 사항이 맞네요. 본문에 그림으로 첨부된 거라 수정이 좀 어려운 점 양해 부탁 드립니다. ^^
