### ISSUE TITLE
p 203 오타 수정

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#13]
[수정 전]
where('id', '&gt;', 10)와 같이 공백이 있는 다음과 같은 PDO ...

[수정 후] 
where('id', '&gt; ', 10)와 같이 공백이 있으면 다음과 같은 PDO ...
혹은 
where('id', ' &gt;', 10)와 같이 공백이 있으면 다음과 같은 PDO ...
- PDO Exception 이 발생한다고 하셨는데 실제 예외는 발생하지 않는 것 같습니다.
  (아니면 예외를 잡아서 아무것도 처리를 하지 않은 것인지 ...)

**Comment by lesstif** [comment]
감사합니다.  :+1: 

확인해 보니 5.1에서는 발생했는데 라라벨 5.2 에서는 PDO Exception 이 발생하지 않습니다.
5.2에서 수정된 것 같은데 어떤 커밋인지는 못 찾았습니다.
