### ISSUE TITLE
p 197 Route::controller deprecated

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#14]
아마도 독자들이 5.2 기준으로 학습을 하고 계실텐데 ...
p 197의 CRUD 실행하기의 Route::controller() 는 5.2에서 deprecated 되었고 5.3에서 제거된것 같습니다.
(제가 5.3에서는 확인을 안해봤습니다.)

**Comment by lesstif** [comment]
책을 라라벨 4. 대부터 작성하다가 중간에 5.0가 출시되어 원고를 재작성하고 5.1이 출시되고 수정하고 탈고 시점에 5.2가 출시되어서 5.2에 맞추긴 했는데 deprecated 된 줄은 몰랐습니다.

알려 주셔서 감사드리며 반영했습니다.
