### ISSUE TITLE
localhost:8000 github인증 하기

### ISSUE THREAD

**Issue by wangjacsi** [lesstif/laravel-todolog#15]
안녕하세요. 
책에 내용 따라하는데 Github 인증에서 

RequestException in CurlFactory.php line 187:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

에러가 나옵니다.
 locahost 환경(localhost:8000 artisan serve)에서 동작시키면 문제가 되는지요?

**Comment by lesstif** [comment]
curl 에 ca 인증서 체인이 설정되지 않은 것 같은데 windows 이거나 또는 curl 을 컴파일해서 설치하신 것 같습니다.

http://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate 에 나온대로 다음 절차대로 수행해 보세요.
1. http://curl.haxx.se/ca/cacert.pem 에서 ca 인증서 다운로드후 저장
2. php.ini 에 다음 내용 추가(cacert.pem 은 맞게 수정해 주세요)

```
curl.cainfo=/path/to/downloaded/cacert.pem
```

**Comment by wangjacsi** [comment]
homestead 환경에서 테스트하니 동작합니다. (localhost가 아닌 todolog.app 홈스테드에서)

궁금한 것이 홈스테드는 자동으로 가상 머신에 데이터베이스도 homestead로 만들어 주는데
그렇다면 여러 프로젝트를 홈스테드 환경에서 돌린다면 데이터베이스를 프로젝트 별로 테스트나 
실행 시에 다시금 재설정 및 생성을 해 주어야 하는것인가요? 

localhost에서는 데이터베이스 네이밍을 자유롭게 하는데 homestead는 어떻게 운용해야 하는지요?

**Comment by lesstif** [comment]
프로젝트 별로 _CREATE DATABASE_ 구문을 사용하여 각각 데이터 베이스를 만들어 주는 것이 좋습니다.

데이터베이스 네이밍은 팀이나 개인이 사용하는 규칙에 맞게 하면 되는데 홈스테드를 포함한 리눅스 환경일 경우 대소문자를 구분하는 것만 주의하면 될 것 같습니다.

**Comment by wangjacsi** [comment]
질문은 멀티 사이트를 홈스테드에 운용 시 데이터베이스는 프로젝트별로 어떻게 맵핑?시켜야 하는가이었습니다. 

방법을 알아보니 .yaml파일에서 데이터베이스부분을 추가해 주면 되는 것이었습니다. 위에 site 순서대로 ...  
databases:
    - homestead
    - laravel_todolog

또한 vagrant up 후에 vagrant provision을 시키면 설정되로 잘 동작함을 확인할 수 있었습니다.

참고 링크
https://laracasts.com/discuss/channels/general-discussion/homestead-multiple-sites-seperate-databases

**Comment by lesstif** [comment]
제가 질문을 잘못 이해했네요.
찾아 주신대로 1. 멀티 사이트 운용시 Homestead.yaml 의 databases 항목에 추가하고 프로비져닝 해주거나 또는 2. 직접 CREATE DATABASE 구문으로 database 를 생성해 주면 됩니다.

1번의  .yaml 에 추가하는 것은 팀으로 개발할 때 동일한 개발 환경을 자동으로 구성할수 있는 장점이 있는 것 같습니다.
