### ISSUE TITLE
310 page 세션 사용

### ISSUE THREAD

**Issue by wangjacsi** [lesstif/laravel-todolog#16]
1. 세션값 github_id 로 코드에 사용됩니다. _ 언더바가 쓰였습니다. 그런데 이후에 사용되는 설명에는 github-id로 언더바가 아닙니다. 
2. Auth::login($authUser)에서 303페이지에 쓰인 코드에는 $user 가 쓰입니다. 
   303페이지: \Auth::login($user) 입니다. 

3.2번에서 Auth의 경우 \Auth와 차이가 어떻게 되는지요? 
둘모두 똑같이 app.php에서 aliase한 Illuminate\Support\Facades\Auth::class, 를 의미하는지요?

**Comment by lesstif** [comment]
1. 세션값 오타 알려주셔서 감사 드리며 정오표에 반영했습니다.
2. \Illuminate\Support\Facades\Auth 파사드가 맞습니다. [laravel ide helper](https://github.com/barryvdh/laravel-ide-helper) 를 설치하시면 IDE 에서 클래스 조회하기가 쉬워집니다.
