### ISSUE TITLE
315 페이지 모델 간 관계

### ISSUE THREAD

**Issue by wangjacsi** [lesstif/laravel-todolog#17]
모델간 관계를 코드를 보면 
public function projects () 등으로 복수형으로 테이블 이름을 명시해 주는 것 같은데요.
책에 코드를 315, 316페이지를 보면 어느때는 복수 어느때는 단수 입니다. 
tasks, user ? (315), project (316) 
라라벨의 명명 규칙이 어떻게 되나요? 헷갈리는데요...

아니면 그저 함수를 정의하기 나름인 것이고
나중에 그저 함수를 호출해서 쓰는 것인가요?

**Comment by lesstif** [comment]
함수 이름을 정의하기 나름이지만 모델간의 관계에 맞게 이름을 정해주는게 관례(?) 입니다.
1. Project 모델의 tasks() 는 하나의 프로젝트는 여러 개의 task 를 가질수 있는 hasMany 이므로 복수형입니다
2. Project 모델은 하나의 User 에 속해있는 beLongsTo 관계이므로 user() 가 됩니다.

**Comment by wangjacsi** [comment]
감사합니다. ^^
