### ISSUE TITLE
348~350 Page: task update 부분

### ISSUE THREAD

**Issue by wangjacsi** [lesstif/laravel-todolog#18]
1. 349페이지: 부트스트랩 datetimepicker 사용 코드
   본문: `$("#due_date").datepicker({`  
   수정: `$("#due_date").datetimepicker({`
   으로 수정 필요
2. 349 페이지
   폼에서 기한 부분 name attribute가 빠져 있습니다. 따라서 업데이트가 되지 않습니다. 
   본문: `<input type="text" class="form-control" value="{{ $task->due_date }}">`
   수정:`<input type="text" class="form-control" name="due_date" value="{{ $task->due_date }}">`

**Comment by lesstif** [comment]
반영했습니다. 알려주셔서 감사 드립니다.
