### ISSUE TITLE
정오표 수정

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#2]
정오표의 아래 부분 삭제 부탁드립니다. 
(원 서적의 내용이 맞습니다.)
혼란을 드려서 죄송합니다.

변경전

<?php foreach ($list as $u): ?>
    <li> <?php echo $u['name']; ?> </li>
<?php endforeach; ?>
변경후

<?php foreach ($list as $u): ?>
    <li> <?php echo $u['name']; ?> </li>
<?php :endforeach; ?>   // 수정

**Comment by lesstif** [comment]
감사합니다. 앞으로도 이상한 부분 있으면 알려 주세요 :+1:
