### ISSUE TITLE
소셜 로그인(github)시 문제입니다.

### ISSUE THREAD

**Issue by joe-funda** [lesstif/laravel-todolog#21]
안녕하세요.
책은 오래 전에 샀다가 최근데 다시 라라벨 공부를 시작했습니다.
지금은 todo를 따라하고 있는데 github 로그인구현하는데 문제가 생겨 글남깁니다.

라라벨 버전은 Laravel Framework version 5.3.26인데 github 연동해서 로그인시 password가 default로 잡혀 있지 않아서 User테이블에 insert를 할수 없다고 나옵니다.

그래서 강제로 User::create(p305)시에 password를 하드코딩으로 넣어 줬는데 github 로그인시 패스워드도 꼭 같이 저장해야하는건가요?

감사합니다.

**Comment by lesstif** [comment]
책은 5.2 기준으로 저술되었는데 5.3 을 기준으로 하셨네요.
5.3 은 database\migrations\2014_10_12_000000_create_users_table.php 파일을 보니 *password* 컬럼에 nullable() 이 빠져서 발생한 것 같습니다.

첫번째 해결책은 다음과 같이 5.2 버전의 라라벨 프로젝트를 생성해서 실습하는 것입니다. 

```sh
composer create-project laravel/laravel laravel-5.2  5.2.*
```

2번째는 database\migrations\2014_10_12_000000_create_users_table.php 의 패스워드에 null 을 허용하도록(_nullable()_ 추가) 변경하고 스키마를 새로 생성하면 됩니다..

**Comment by joe-funda** [comment]
이제 이해가 됐네요~ 감사합니다~
