### ISSUE TITLE
p38 예제1.5 의존성 주입 적용 

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#3]
아래 소스에서  class의  implements RepositoryInterface 부분은 삭제 되어야 할것 같습니다.
RepositoryInterface 인터페이스를 구현하는 것은 UserRepository 가 아니라 주입되는 $repository 객체의 class 가 아닐까요?

 <?php

class UserRepository implements RepositoryInterface {
    private $repository;

```
public function __construct(RepositoryInterface $repository) {
    $this->repository = $repository;
}
```

}

**Comment by lesstif** [comment]
@linuxwife 맞습니다. 저러면 DI 가 아니네요. 
pseudo code 라 꼼꼼하게 되어 있지 않은 점 사과 드립니다.
