### ISSUE TITLE
한글 깨짐 현상

### ISSUE THREAD

**Issue by y-minhoon** [lesstif/laravel-todolog#4]
책의 104 Page에 있는 뷰를 확인하고 있습니다.
[예제 3.7]을 입력하고 실행하면 정상적으로 한글이 나옵니다.

그런데 [예제 3.8]과 [예제3.9]를 실행하면 한글이 깨지는데요..
어떤 걸 확인해야 할까요?

도서 내용을 그대로 제가 작성한 소스는 다음과 같습니다.

**app/Http/routes.php**

`Route::get('hello/html', function() {
    return view('hello.html');
});`

**resources/views/hello/html.php**

`<!doctype html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>OK</title>
    </head>
    <body>
        <h1>라라벨 Response!</h1>
    </body>
</html>`

**Comment by lesstif** [comment]
@y-minhoon 한글이 깨진다면 소스 파일(EX: resources/views/hello/html.php)의 인코딩이 UTF-8 이 아닌 것 같습니다.

사용하시는 에디터의 인코딩 설정을 확인하고 UTF-8 로 다시 저장하면 됩니다.(BOM - Byte Order Mark 가 없어야 합니다.)

윈도라면 간단하게 notepad 에서 "다른 이름으로 저장" 을 선택하고 인코딩을 **UTF-8**로 해 주면 됩니다.

![image](https://cloud.githubusercontent.com/assets/404534/16296940/631e2308-3969-11e6-984a-928e7332a59f.png)

**Comment by y-minhoon** [comment]
router에서 한글을 입력하면 깨지지 않아서 파일 인코딩 방식의 문제인지는 몰랐습니다.
덕분에 해결되었습니다.
그런데 router에서는 깨지지 않았는데 view에서 한글을 입력하면 깨지는 이유가 정확히
무엇인지 알 수 있을까요?

**Comment by lesstif** [comment]
routes.php 가 UTF-8 BOM 으로 인코딩되어 있어서 에디터에서 UTF-8 을 식별하여 한글 문제가 없지 않았을까 추측했는데 지금 확인해 보니 routes.php 은 영어만 있으니 인코딩이 당연히 ascii 로 되어 있네요.

개발 환경이 달라서 왜 view 파일 작성시 문제가 되었는지 제가 원인을 파악하기는 어려울 것 같고 라라벨로 개발하시려면 이런 문제 방지를 위해 에디터의 기본 파일 인코딩을 UTF-8 로 설정하고 사용하는 것을 권장합니다.

p.261의 **주의사항** 에 해당 내용을 넣어 놨는데 책 중간 부분이라 아직 못 보셨을 것 같네요. 만약 개정판을 내게 된다면 "UTF-8 설정"을 앞 부분으로 옮겨야 겠습니다. :)

**Comment by y-minhoon** [comment]
예.. 감사합니다... 진행하다가 궁금한 사항은 추가로 문의하겠습니다.
