### ISSUE TITLE
p203 SQL 조건 누락 수정

### ISSUE THREAD

**Issue by linuxwife** [lesstif/laravel-todolog#6]
[수정 전]

최종 검색 조건은 아래와 같이 SQL로 변환되어 id가 10보다 크고 20보다 작은 모델을 name 칼럼을 기준으로 내림차순으로 정렬한후에 ..

select \* from `task` where `id` > '10' and `id` < '20' order by `name` desc limit 3 offset 5;

[수정 후]

최종 검색 조건은 아래와 같이 SQL로 변환되어 id가 10보다 크고 20보다 작고 **name 칼럼이 'Ta'로 시작하는**  모델을 name 칼럼을 기준으로 내림차순으로 정렬한후에 ..

select \* from `task` where `id` > '10' and `id` < '20' **and `name` like 'Ta%'** order by `name` desc limit 3 offset 5;

**Comment by lesstif** [comment]
감사합니다. :+1:  다음부터는 Pull Request 로 보내주셔도 됩니다.
