### ISSUE TITLE
homestead의 production 사용?

### ISSUE THREAD

**Issue by y-minhoon** [lesstif/laravel-todolog#9]
책과 직접적인 연관이 없는 내용이라 죄송합니다. 

homestead를 사용하니 쉽게 provisioning되는데요..
실제로 homestead를 이용해서 운영환경에서 사용하는 경우가 있는지요?
구글에서 검색하니 virtual machine이니 리눅스에 직접 설치하라는식의 의견이 많은데
혹시 운영환경은 어떻게 구축하셨는지요?

**Comment by lesstif** [comment]
@y-minhoon 홈스테드는 동일한 개발환경을 빠르고 쉽게 구축하기 위한 용도라고 보시면 됩니다.

가상 머신이다 보니 속도가 매우 느린 문제가 있으니 운영 환경에서는 직접 패키지를 설치하고 디플로이해야 합니다.

책의 13장 "라라벨 배포" 를 참고하시고 우분투에 디플로이 하기 위한 스크립트는 다음 gist 를 참고하세요
- [우분투 14 LTS](https://gist.github.com/lesstif/5bd471dfa6c7fd15e0af)
- [우분투 16 LTS](https://gist.github.com/lesstif/789b69158028040f234c8b853ecf13b6)

**Comment by y-minhoon** [comment]
최초 책 목차에서 13장이 배포인 것을 보았는데 읽다보니 잊고 있었네요.. 답변 감사합니다.
